---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: astrid-framework-common
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: astrid-framework
  validation: client

